### ISSUE TITLE
[And] Firebase / Firebase UI

### ISSUE THREAD

**Issue by lutics** [sunnydevstudio/testbed#2]
다음 Lib 적용

- [x] Firebase 계정 및 도메인 획득
- [x] Firebase Android
- [x] Firebase UI

적용 후

- [x] [Getting started with Firebase and Android - Firecasts #1](https://youtu.be/B1rlT5KQ0yE)
- [x] [Retrieving data in realtime with Firebase Events - Firecasts #2](https://www.youtube.com/watch?v=2FRBDXBs30Y)
- [x] [Realtime RecyclerViews with FirebaseUI - Firecasts #3](https://www.youtube.com/watch?v=2J6spwAVP0M)

**Comment by lutics** [comment]
[Getting started with Firebase and Android - Firecasts #1](https://youtu.be/B1rlT5KQ0yE)
[Retrieving data in realtime with Firebase Events - Firecasts #2](https://www.youtube.com/watch?v=2FRBDXBs30Y)
[Realtime RecyclerViews with FirebaseUI - Firecasts #3](https://www.youtube.com/watch?v=2J6spwAVP0M)
[Introduction to Firebase Security Rules - Firecasts #7](https://youtu.be/eUfSpktxNeQ)

**Comment by lutics** [comment]
Security Rule 등 기본 예제 외에는 별도 추가 이슈로 처리
